#!/bin/bash

##
# baselineに含まれる重複したPMIDの一覧を取得する
# 初回、または一年の最初に実行すること
##

# プロパティ
WORK=/work
BASE_URL=ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline


# ディレクトリの作成
mkdir -p $WORK/baseline

# baselineのダウンロード
cd $WORK/baseline
wget  -r -nd -nc -c -A xml.gz $BASE_URL 2>/dev/stdout


# baseline内の重複したPMIDを抜きだし、最新の更新日の値とペアで出力する
ruby /pubmed_dup_check.rb



